name: "Zordon A.I CodeReviewer"
description: "Use ZordonAI to code review pull requests"
inputs:
  github_token:
    description: "GitHub token to access repositories"
    required: false
    default: ${{ github.token }}
  palm_api_key:
    description: "PaLM API key"
    required: true
runs:
  using: "node20"
  main: "dist/index.js"
