name: "Zordon A.I CodeReviewer"
description: "Use ZordonAI to code review pull requests"
inputs:
  github_token:
    description: "GitHub token to access repositories"
    required: false
    default: ${{ github.token }}
  openai_api_key:
    description: "OpenAI API key"
    required: false
    default: ""
  bard_api_cookie:
    description: "Google Bard API Cookie"
    required: false
    default: ""
  palm_api_key:
    description: "Google PaLM API key"
    required: false
    default: ""
  exclude_files:
    description: "Glob patterns to exclude files"
    required: false
    default: ""
runs:
  using: "node20"
  main: "dist/index.js"
